TRAIN_PATH: /home/myeghiaz/Storage/Discriminator/Disc-0.125m-384px/train
VALIDATION_PATH: /home/myeghiaz/Storage/Discriminator/Disc-0.125m-384px/validation
IMAGE_FORMAT: .png
SHUFFLE: True
BATCH_SIZE: 16
BASE_LR: 0.0001
LR_GAMMA: 0.3
N_EPOCHS: 3
SAVE_FREQ: 1000
EVAL:
    FREQ: 100
    MAX_ITER: 10
OUTPUT_DIR: saved_models/basic-discriminator
DEVICE: cuda
MODEL:
    NAME: resnet101
    # WEIGHTS: saved_models/basic-discriminator/model_final.pth
    WEIGHTS: 
LOSS:
    NAME: BCELoss
    COEFFICIENT: 1.0