TRAIN_PATH: /home/myeghiaz/Storage/Discriminator/Disc-0.125m-384px/train
VALIDATION_PATH: /home/myeghiaz/Storage/Discriminator/Disc-0.125m-384px/validation
IMAGE_FORMAT: .png
SHUFFLE: True
BATCH_SIZE: 16
BASE_LR: 0.01
N_EPOCHS: 5
OUTPUT_DIR: saved_models/basic-discriminator
DEVICE: cuda
MODEL:
    NAME: resnet101
    WEIGHTS: 
LOSS:
    NAME: BCELoss