TRAIN_PATH: /home/myeghiaz/Storage/Discriminator/Disc-0.125m-384px/train
VALIDATION_PATH: /home/myeghiaz/Storage/Discriminator/Disc-0.125m-384px/validation
IMAGE_FORMAT: .png
SHUFFLE: True
BATCH_SIZE: 16
BASE_LR: 0.00001
N_EPOCHS: 5
SAVE_FREQUENCY: 1000
OUTPUT_DIR: saved_models/basic-discriminator
DEVICE: cuda
MODEL:
    NAME: resnet101
    # WEIGHTS: saved_models/basic-discriminator/model_final.pth
    WEIGHTS: 
LOSS:
    NAME: BCELoss
    COEFFICIENT: 1.0